import Link from "next/link";
const stories=[{slug:"slow-skincare",cat:"SKINCARE",title:"The art of a slower, simpler skincare routine",desc:"A thoughtful edit of the essentials that help your skin feel like itself, only happier.",image:"photo-1556229010-6c3f2c9ca5f8",read:"6 MIN READ"},{slug:"five-minute-face",cat:"MAKEUP",title:"The five-minute face, reimagined",desc:"Fresh skin, softly defined eyes, and a little colour that looks like you.",image:"photo-1487412720507-e7ab37603c6f",read:"4 MIN READ"},{slug:"better-wash-day",cat:"HAIRCARE",title:"A better wash day starts before the shower",desc:"Small pre-wash rituals that make every strand feel considered.",image:"photo-1522337360788-8b13dee7a37e",read:"5 MIN READ"},{slug:"evening-reset",cat:"WELLNESS",title:"Make room for your evening reset",desc:"A few gentle cues to help the day come to a softer close.",image:"photo-1515377905703-c4788e51af15",read:"3 MIN READ"}];
const photo=(id:string,w=1000)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
export default function Home(){return <main><div className="announcement">A little more intention, a little more glow. <a href="#latest">Explore the journal ↗</a></div>
<header className="header"><Link className="logo" href="/">glow<span>.</span></Link><nav><a href="#skincare">Skincare</a><a href="#makeup">Makeup</a><a href="#haircare">Haircare</a><a href="#wellness">Wellness</a><Link href="/about">Our story</Link></nav><a className="header-cta" href="#newsletter">The Sunday Edit ↗</a></header>
<section className="hero"><div className="hero-copy"><p className="eyebrow">✳ &nbsp; THE BEAUTY JOURNAL</p><h1>Beauty is a<br/><em>feeling,</em> not a finish.</h1><p className="intro">Thoughtful notes on skincare, modern rituals and the little things that make you feel more like you.</p><a className="button" href="#latest">Read the latest <span>↗</span></a><p className="hero-note">GOOD SKIN DAYS START WITH<br/><b>GETTING TO KNOW YOURSELF.</b></p></div><div className="hero-visual"><img src={photo("photo-1611930022073-b7a4ba5fcccd",1400)} alt="Skincare essentials in soft morning light"/><div className="stamp">YOUR DAILY<strong>glow</strong>RITUAL</div><div className="caption">THE EVERYDAY EDIT — ISSUE NO. 08</div></div></section>
<div className="ticker">SKIN, WITH INTENTION　 ✳　 MAKEUP, MADE PERSONAL　 ✳　 GOOD HAIR DAYS　 ✳　 WELLNESS, EVERYDAY　 ✳</div>
<section className="section" id="latest"><div className="section-title"><div><p className="eyebrow">FRESH FROM THE JOURNAL</p><h2>A little <em>something</em> for you.</h2></div><span className="browse">THE LATEST NOTES ↗</span></div><div className="stories">{stories.map(s=><article id={s.cat.toLowerCase()} className="story" key={s.slug}><Link className="story-image" href={`/article/${s.slug}`}><img src={photo(s.image)} alt="" loading="lazy"/><span>↗</span></Link><div className="meta"><b>{s.cat}</b><span>{s.read}</span></div><h3><Link href={`/article/${s.slug}`}>{s.title}</Link></h3><p>{s.desc}</p></article>)}</div></section>
<section className="manifesto"><img src={photo("photo-1608248543803-ba4f8c70ae0b",1100)} alt="A calm, sunlit beauty ritual"/><div><p className="eyebrow">A NOTE FROM US</p><h2>Less noise.<br/><em>More you.</em></h2><p>We believe beauty should feel like coming home to yourself. No impossible standards, no ten-step rules. Just honest advice, lovely discoveries and rituals worth keeping.</p><Link className="underlink" href="/about">Get to know Glow ↗</Link></div></section>
<section className="section categories"><p className="eyebrow">FOLLOW YOUR CURIOSITY</p><h2>Your kind of <em>glow.</em></h2><div className="category-grid"><a href="#skincare"><img src={photo("photo-1570172619644-dfd03ed5d881",700)} alt="Skincare"/><strong>Skin notes ↗</strong></a><a href="#makeup"><img src={photo("photo-1522335789203-aabd1fc54bc9",700)} alt="Makeup"/><strong>Makeup mood ↗</strong></a><a href="#haircare"><img src={photo("photo-1527799820374-dcf8d9d4a388",700)} alt="Haircare"/><strong>Hair rituals ↗</strong></a><a href="#wellness"><img src={photo("photo-1540555700478-4be289fbecea",700)} alt="Wellness"/><strong>Soft living ↗</strong></a></div></section>
<section className="newsletter" id="newsletter"><p className="eyebrow">A NOTE FOR YOUR INBOX</p><h2>Your Sunday, <em>well spent.</em></h2><p>One thoughtful letter, a few lovely finds, and a softer start to your week.</p><form action="#newsletter" method="get"><label className="sr" htmlFor="email">Email address</label><input id="email" name="email" type="email" placeholder="Your email address" required/><button type="submit">Count me in ↗</button></form><small>Newsletter sign-up is a design preview; subscriptions are not collected yet.</small></section>
<footer><div className="footer-main"><Link className="logo" href="/">glow<span>.</span></Link><p>Beauty, thoughtfully.<br/>A journal for feeling good in your own skin.</p><div><Link href="/about">Our story</Link><a href="#latest">The journal</a><a href="#newsletter">Newsletter</a></div></div><div className="footer-bottom"><span>© 2026 GLOW JOURNAL</span><span>MADE WITH CARE, ALWAYS ✳</span><a href="#top">BACK TO TOP ↑</a></div></footer></main>}